swagger: '2.0'
info:
  title: Invoice API
  version: "0.1"
  description: Invoices microservice API
consumes:
  - application/json
produces:
  - application/json
basePath: "/api"
securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header
    x-authentication-scheme: Bearer
    x-bearerInfoFunc: app.decode_token
paths:
  /invoice/create:
    post:
      tags: [ Invoices ]
      operationId: app.create_invoice
      summary: Create new invoice
      parameters:
        - $ref: '#/parameters/invoice_body'
      responses:
        200:
          description: Created OK
        400:
          description: Try again
  /invoice/find_invoice_by_id/{invoice_id}:
    get:
      tags: [ Invoices ]
      operationId: app.get_invoice_by_id
      summary: Get invoice by id
      parameters:
        - $ref: '#/parameters/invoice_id'
      responses:
        200:
          description: return Invoice by Id
        404:
          description: Invoice not found
  /invoice/find_invoices_by_user/{user_id}:
    get:
      tags: [ Invoices ]
      operationId: app.get_invoices_by_user
      summary: Get invoice by user
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: return Invoice by User
        404:
          description: Invoice not found
  /invoice/find_all:
    get:
      tags: [ Invoices ]
      operationId: app.get_all
      summary: Get all invoices
      responses:
        200:
          description: return all Invoices
        404:
          description: Invoices not found
  /invoice/delete/{id}:
    delete:
      tags: [ Invoices ]
      operationId: app.delete_invoice
      summary: Delete invoice by id
      parameters:
        - $ref: '#/parameters/id'
      responses:
        204:
          description: Invoice successfully deleted
        404:
          description: Invoice not found
parameters:
  user_id:
    name: user_id
    description: The ID of the User
    in: path
    type: string
    required: true

  id:
    name: id
    description: The ID of the Invoice
    in: path
    type: string
    required: true

  invoice_id:
    name: invoice_id
    description: The ID of the Invoice
    in: path
    type: string
    required: true

  invoice_body:
    name: invoice_body
    description: Required parameters for invoice
    in: body
    schema:
      required:
        - user_id
        - transaction_id
        - item_list
      properties:
        user_id:
          type: integer
        transaction_id:
          type: integer
        item_list:
          type: array